Add support for Django 3.2 - 5.0 and Python 3.10 - 3.12
Dunedan/django-lockdown pull request #21
Opened 2024-02-21 09:12 UTC by browniebroke

Update official support matrix for Django and Python versions to match upstream support. 

FWIW, we already use this package with Python 3.11 and Django 4.2 (soon 3.12 & 5.0), but I thought it was worth updating official support on CI.

--- 

Thanks a lot for opening a pull request. :tada:

To ensure your pull request can get merged as fast as possible, please check
all points in the following list:

- [ ] When adding new code add corresponding tests as well.
- [ ] Ensure your code follows the [Python Style Guide (PEP8)][1] and the
      [Docstring Conventions (PEP257)][2].
- [ ] Update the `AUTHORS.rst`, `CHANGES.rst` and `README.rst` as necessary.
- [ ] Check that [continuous integration (CI)][1] runs succeed after you opened
      the pull request and fix the issues it detects.

Please also replace this template with a description of your changes before you
open the pull request.

[1]: https://www.python.org/dev/peps/pep-0008/
[2]: https://www.python.org/dev/peps/pep-0257/
[3]: https://github.com/Dunedan/django-lockdown/actions

2025-03-22 15:24 UTC, browniebroke commented
It took a while to get this into a green state ready to merge, but I think it's now good. Since that was open, Django 5.1 and Python 3.13 were released, Python 3.8 went EOL and Django 5.2 is just around the corner.

I'm happy to update (add + remove) support accordingly but I'd rather do it in a follow up pull request, and it might be best to make a release before we do so.

2025-03-22 20:41 UTC, browniebroke commented
@Dunedan are you still interested in keeping this project going? I just noticed that the last commit to main is 4 years old... While the project is probably "done" and doesn't need much attention, Django keeps evolving.

If you no longer use Django (life moves on), you may consider a move to @django-commons

2025-03-25 07:24 UTC, Dunedan requested changes
Hi @browniebroke,

Thanks a lot for this contribution. As long as there are users of django-lockdown, I'm interested in keeping it maintained. Unfortunately I entirely missed this PR when you opened it, so thanks for the heads up.

I have a bunch of comments, but I believe we can get fix them fairly quickly.

> Since that was open, Django 5.1 and Python 3.13 were released, Python 3.8 went EOL and Django 5.2 is just around the corner.

My policy has always been to only support versions of Python and Django which aren't EOL. I'd appreciate if you'd remove support for Python 3.8 and Django <4.2 as well.

2025-03-25 07:24 UTC, Dunedan commented on .pre-commit-config.yaml
> +  #         - setuptools
Updating prospector to the latest version works for me:

```suggestion
  - repo: https://github.com/prospector-dev/prospector/
    rev: v1.16.0
    hooks:
      - id: prospector
        additional_dependencies:
          - django
```

pylint complains about some code quality rules afterwards, but those should be fixable.

2025-03-25 07:24 UTC, Dunedan commented on .pre-commit-config.yaml
> +  python: python3.11
I'm not sure why you set this, but doing so prevents `pre-commit` from running successfully when Python 3.11 isn't present. That's annoying when running `pre-commit` locally, so please remove it again.

2025-03-25 07:24 UTC, Dunedan commented on .github/workflows/main.yml
> +          # - "pypy3.9"
It'd be great to keep testing with PyPy. Could you please check if it works with PyPy 3.10?
```suggestion
          - "pypy3.10"
```

2025-03-25 09:23 UTC, browniebroke commented on .pre-commit-config.yaml
> +  #         - setuptools
I was trying to avoid getting too many unrelated fixes in this PR, but I can add them if you don't mind. Or I can submit a PR to fix the CI before getting further on this? Let me know if you have a preference

2025-03-25 09:23 UTC, browniebroke commented on .pre-commit-config.yaml
> +  python: python3.11
That was an earlier attempt at fixing `prospector`. I had a strange error that seemed to indicate a breakage due a recent version of Python

2025-03-25 09:24 UTC, browniebroke commented on .github/workflows/main.yml
> +          # - "pypy3.9"
I'll take a look

2025-03-25 10:17 UTC, browniebroke commented on .pre-commit-config.yaml
> +  #         - setuptools
I've extracted this in https://github.com/Dunedan/django-lockdown/pull/23 and hit a bit of blocker with prospector. I might try again later but I'm not familiar with the tool so any suggestions/pointers would be appreciated. Thanks

2025-03-25 14:10 UTC, Dunedan commented on .pre-commit-config.yaml
> +  #         - setuptools
> I was trying to avoid getting too many unrelated fixes in this PR, but I can add them if you don't mind. Or I can submit a PR to fix the CI before getting further on this? Let me know if you have a preference

I'm fine with both approaches, but splitting different topics into different PRs is probably the easier way. :+1:

2025-03-27 16:30 UTC, browniebroke commented
I've also added Python 3.13 and Django 5.1, as it all passed.

2025-03-28 09:11 UTC, Dunedan commented
Thanks a lot for your contributions. Very much appreciated. This looks good to me and I'm going to merge it as well.

I'll wait a week or so until Django 5.2 gets released to add formal support for it too, before releasing a new version of `django-lockdown`, which will then be available via PyPI.

2025-03-28 09:11 UTC, merged